### ISSUE TITLE
comparison with vue-cli-plugin-ssr

### ISSUE THREAD

**Issue by dohomi** [vueneue/vueneue#11]
Hi there

just found your plugin and want to know what are the benefits of this package compared to https://github.com/Akryum/vue-cli-plugin-ssr. Aren't this similar efforts? Looking for an alternative to NuxtJS and found this two packages, would like to know where the main differences. Thanks!

**Comment by Akryum** [comment]
Friendly competition is healthy! 😸

**Comment by dohomi** [comment]
ok fair enough :-)
