### ISSUE TITLE
Easy way to use process.env variables?

### ISSUE THREAD

**Issue by Tjark-Kuehl** [vueneue/vueneue#16]
Hi there,
i have a question about env variables like they are implemented in nuxtjs.

Like so
```
module.exports = {
    /*
    ** Env Variables
    */
    env: {
        PROJECT_TITLE: 'Title',
        API_URL
    }
}
```

Is there currently a way that I can access process.env variables like that?
Because some variables are already in there
```
{ NODE_ENV: 'development',
  VUE_APP_CLI_UI_URL: '',
  VUE_APP_I18N_FALLBACK_LOCALE: 'en',
  VUE_APP_I18N_LOCALE: 'de',
  BASE_URL: '/' }
```

**Comment by chymz** [comment]
See: https://cli.vuejs.org/guide/mode-and-env.html
