### ISSUE TITLE
Hot module reload does not work on Windows: Error in connection establishment: net::ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by valyakin** [vueneue/vueneue#2]
Client can not connect to hmr WebSocket on Windows.

![screenshot_5](https://user-images.githubusercontent.com/32761513/42376055-35a77574-8137-11e8-919b-8125e9a48765.png)

It seems that setted by default 0.0.0.0 is not valid address.
It seems that 127.0.0.1 will be a reasonable option that works both on windows and linux.

Please reffer to simmilar issues:
https://github.com/Hashnode/mern-starter/issues/232

Temporary workaround: 
`cross-env HOST=127.0.0.1 vue-cli-service ssr:serve`

Probably it will be a great idea to point in docs how env.HOST influences plugin behavior.
Or even better to make it support `--host` which is already being used in `ssr:serve` command

Suggested solution in PR https://github.com/vueneue/vueneue/pull/1

**Comment by chymz** [comment]
Fixed in `v0.2.7` !
