### ISSUE TITLE
TypeError: redirect is not a function

### ISSUE THREAD

**Issue by camwhite** [vueneue/vueneue#26]
### Version
*0.3.15*

### Issue

I'm facing a situation where the error handler seems to be taking precedence and executing before my axios interceptor. Which I'm hoping to use to catch 401s coming from my API and redirect accordingly.

## Main.js function code
I'm attempting to do the boot time logic here instead of like the [example](https://github.com/vueneue/examples/blob/master/src/plugins/httpClient.js#L78)

```js
export default function ({ app, router, store, redirect, ctx }) {
  // check for and set token into store
  if (!process.client) {
    if (ctx.headers.authorization) {
      const [ bearer, token ] = ctx.headers.authorization.split(' ')
      store.commit('setToken', token)
    }
  } else {
    const Cookies = require('js-cookie')
    store.commit('setToken', Cookies.get('token'))
  }

  axios.defaults.baseURL = process.client ? '/api' : process.env.VUE_APP_API_URL + '/api'
  axios.interceptors.request
    .use((request) => {
      store.commit('addRequest')
      const { token } = store.getters
      if (token) {
        request.headers['Authorization'] = `Bearer ${token}`
      }
      return request
    })
  axios.interceptors.response
    .use((response) => {
      store.commit('addResponse')
      return response
    }, (error) => {
      // grab 401s and redirect
      if (error.response.data.statusCode === 401) {
        store.commit('setToken', null)
        store.commit('setCurrentUser', null)
        redirect('/auth')
      }
      return Promise.reject(error)
    })

  // client side navigation guards
  router.beforeEach((to, from, next) => {
    if (to.matched.some(record => record.meta.requiresAuth) && process.client) {
      if (!store.getters.token) {
        next('/auth')
      } else {
        next()
      }
    } else if (to.matched.some(record => record.meta.guest) && process.client) {
      if (store.getters.token) {
        next('/')
      } else {
        next()
      }
    } else {
      next()
    }
  })

  return new Vue({
    router,
    store,
    render: h => h(App)
  })
}
```
@chymz your auth example was helpful, but I must be doing something wrong on the vuex integration. Do find this unneeded? With my setup, currently, I make my API calls inside my actions. Should I do as you have done and make the calls off the vue instance? Any input or help would be very appreciated.

## Edit

After some further investigation the error it catches on is `TypeError: redirect is not a function`

**Comment by chymz** [comment]
Indeed `redirect` must be defined here... working on it !

**Comment by camwhite** [comment]
Do you have an ETA? No rush, just wondering.

**Comment by camwhite** [comment]
Thanks @chymz incredible work on this, my app flies, so fast!

**Comment by chymz** [comment]
`0.3.16` released. Does it fix your issue ? Thanks !

**Comment by camwhite** [comment]
We let know as soon as I fire it up, probably later today. Thanks for the quick pathch!

**Comment by chymz** [comment]
This action is called on all routes, if defined in Vuex store:

- (SSR) https://github.com/vueneue/vueneue/blob/master/packages/%40vueneue/ssr-core/server/startApp.js#L30
- (SPA) https://github.com/vueneue/vueneue/blob/master/packages/%40vueneue/ssr-core/client/startApp.js#L75

As you can see, execution order is :

- Global and routes middlewares
- `onHttpRequest` store action
- And finally `asyncData` on pages components

Issue with redirect function is fixed now ? Can you open a new issue for `onHttpRequest` ? I'll take a look soon if there is any issue with it !

**Comment by camwhite** [comment]
Reopening because I'm still hitting this error...

```
{ Error: ROUTER_REDIRECT
    at __webpack_exports__.default (webpack-internal:///./node_modules/@vueneue/ssr-core/utils/redirect.js:8:25)
    at eval (webpack-internal:///./src/plugins/interceptors.js:46:16)
    at process._tickCallback (internal/process/next_tick.js:68:7) statusCode: 301, href: '/auth' }
```

**Comment by chymz** [comment]
Sorry, but If you don't show a bit of code it will be hard to me to help you !

Where do you use `route` ?

**Comment by camwhite** [comment]
Inside a plug-in or in main function it is undefined.

**Comment by chymz** [comment]
At this moment Vue router is not ready, so route is not defined.
Try to use `router.currentRoute` instead.

For your error: redirect is designed to be called in `asyncData` or in a middleware.

I close this issue because original issue seems to be fixed.

**Comment by camwhite** [comment]
Okay, could this interceptor pattern be translated to a middleware? Because I'm struggling on how to solve dealing with invalid or expired tokens otherwise. Also if the `router` is available why would `router.replace` not work?

You may want to update the [docs](https://github.com/vueneue/vueneue/issues/26#issuecomment-414163992) if redirect is not designed to work in the init function.

**Comment by chymz** [comment]
Well, your use case is interesting, I'll look how Nuxt handle this.

I need to think about it !
