### ISSUE TITLE
[vue-router] Duplicate named routes definition: { name: "pageNotFound", path: "*" }

### ISSUE THREAD

**Issue by shijunti19** [vueneue/vueneue#38]
[vue-router] Duplicate named routes definition: { name: "pageNotFound", path: "*" }
![1](https://user-images.githubusercontent.com/5392211/45525277-db188f80-b804-11e8-8179-223b13dc48f5.png)
```js
console.log(routes)
const route = new Router({
  routes: routes,
  mode: process.ssr ? 'history' : 'hash'
  //base: process.env.BASE_URL,
})
export default () => {
  return route
}
```

![2](https://user-images.githubusercontent.com/5392211/45525352-25017580-b805-11e8-8fe3-1cf097fdbb3b.png)

**Comment by chymz** [comment]
Hi, sorry but you need to show more code and more details: what is `routes` in your example code ? Is this your `router.js` file ?

If yes first error I see, is that `new Router` need to be placed in your `export default () =>`.

**Comment by shijunti19** [comment]
```js
import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
let routesStr = ['index', 'about', 'video']
let routes = []
routesStr.forEach(val => {
  const path = require('../pages/' + val + '/route.js')
  routes = routes.concat(path.default)
})
const route = new Router({
  routes: routes,
  mode: process.ssr ? 'history' : 'hash'
  //base: process.env.BASE_URL,
})
export default () => {
  return route
}
```
