### ISSUE TITLE
Passing parameters (options) to plugins

### ISSUE THREAD

**Issue by KleinMaximus** [vueneue/vueneue#41]
It would be convenient if in the plugins block of the file neue.config.js it would be possible to set any optional parameters passed to plugins.

In config:
```
plugins: {
  pluginAxios: {
    src: '@/plugins/axios',
    params: { /* ... */ }
  },
}
```

In plugin:
```
export default async (ctx, params) => {
  // ...
}
```

I think it's not hard to do :)

**Comment by chymz** [comment]
Not hard but dangerous actually: this will imply to include `neue.config.js` in your final bundle and this file can contains some sensible data (e.g HTTPS configuration)

Anyway, this will be handled on next version ;)

**Comment by chymz** [comment]
Implemented in [UVue](https://github.com/universal-vue/uvue)
