### ISSUE TITLE
SyntaxError: Unexpected token ... when npm run test:e2e with cypress 

### ISSUE THREAD

**Issue by thenickname** [vueneue/vueneue#45]
E2E tests throw an error originating in @vueneue/ssr-core/build/NeueApi.js:160

<img width="726" alt="bildschirmfoto 2018-10-14 um 09 58 57" src="https://user-images.githubusercontent.com/1009726/46914003-cfe98880-cf97-11e8-9ad3-9056a05c16da.png">

It would seem cypress does not understand spread syntax.

My setup uses following cli plugins:
* typescript
* vueneue
* pwa

Everything else is pretty much standard setup.

**Comment by chymz** [comment]
Good catch, I'll look into it soon !

**Comment by chymz** [comment]
https://github.com/cypress-io/cypress/issues/2069

**Comment by chymz** [comment]
@thenickname can you test `0.2.22` ?

**Comment by thenickname** [comment]
@chymz you mean 0.**3**.22 don't you?

anyway, using 0.3.22 e2e test are working again! Thank you!

It should be mentioned that I got a lot of warnings about missing peer deps for babel 7 beta 47. I had to first install that dependency and after that it started working...
