### ISSUE TITLE
CORS support for vue ssr server?

### ISSUE THREAD

**Issue by JimmyLv** [vueneue/vueneue#51]
Hey, When I run my website in cypress, it's blocked by CORS:

![image](https://user-images.githubusercontent.com/4997466/47473225-66456600-d844-11e8-9d0f-9172eb5f8c94.png)

**Comment by chymz** [comment]
You have to add CORS support to your casaba server.

Side note: you have 3 issues opened on this repository, can you answer questions in these issues ?
