### ISSUE TITLE
vue-intersect - Server error "Unexpected token import" for certain packages when using ssr:serve

### ISSUE THREAD

**Issue by sjoerdvisscher** [vueneue/vueneue#53]
You can see it if you check out this repo: https://github.com/sjoerdvisscher/test-ssr
This is just a brand new repo created with Vue cli, where I added @vueneue/vue-cli-plugin-ssr and the vue-intersect package.
If you run `yarn serve` and go to the homepage you don't get any errors, but if you run `yarn ssr:serve` and go to the homepage you get the server errror  "Unexpected token import".

**Comment by chymz** [comment]
Well this package has 2 problems:

- Distributed code is not correctly transpiled, to resolve this, add below code to `vue.config.js`:
```js
module.exports = {
  transpileDependencies: ['vue-intersect'],
};
```
- Then this package is not SSR compatible: https://github.com/heavyy/vue-intersect/pull/2 (and seems unmaintained ?)

So you have to implements some code to make it SSR compatible.

First create a plugin `src/plugins/VueIntersect.js`:

```js
import Vue from 'vue';
import Intersect from 'vue-intersect';

Vue.component('intersect', Intersect);
```

Then include it only for client side, in `neue.config.js`:

```js
module.exports = {
  plugins: {
    intersect: {
      src: '@/plugins/VueIntersect',
      ssr: false,
    },
  },
};
```

Then use it in your templates with the `no-ssr` component.

**Comment by sjoerdvisscher** [comment]
Thanks a lot! Works like a charm.
