### ISSUE TITLE
[feature] Separate styles for modern build

### ISSUE THREAD

**Issue by academici** [vueneue/vueneue#55]
"Green browsers" support attribute "module" on tag script, old browsers use scripts with attribute "nomodule". But tag link no support "nomodule".
### Idea ###

Create config option modernBrowsers
```js
modernBrowsers = [
    'Chrome >= 60',
    'Safari >= 10.1',
    'iOS >= 10.3',
    'Firefox >= 54',
    'Edge >= 15',
  ]
```

Configure postcss.config.js
```js
const isModern = process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD
let autoprefixerConfig = {}

if(isModern) {
  autoprefixerConfig.browsers = modernBrowsers
}

module.exports = {
  plugins: {
    autoprefixer: {
      ...autoprefixerConfig,
    },
  },
};
```
Files were generated in dist folder and precache-manifest.

Create middleware using useragent parser and modernBrowsers option. 

In html file include needed styles.

what do you think of this idea?

**Comment by chymz** [comment]
Interesting ! But this will need to do some hacks in `vue-server-renderer` package.

I keep this for next version !

**Comment by chymz** [comment]
Moved to: https://github.com/universal-vue/uvue/issues/3
