### ISSUE TITLE
vue-meta not updated on the first rendered spa route 

### ISSUE THREAD

**Issue by germsb** [vueneue/vueneue#56]
Hello, little issue with spaPaths:
```html
<!DOCTYPE html>
<html data-vue-meta-server-rendered data-html-attrs>
    <head></head>
    <body data-body-attrs>
        <div id="app"></div>
        <script data-vue-spa>
            window.__SPA_ROUTE__ = true;
        </script>
        <script src=/js/chunk-vendors.8f56f9c7.js></script>
        <script src=/js/app.8874105a.js></script>
    </body>
</html>
```
As explained in the [vue-meta documentation](https://github.com/declandewet/vue-meta#how-to-prevent-the-update-on-the-initial-page-render), if the `data-vue-meta-server-rendered` attribute is set, vue-meta is not updated on the first render

**Comment by chymz** [comment]
Thanks for reporting, I will fix this soon !

**Comment by chymz** [comment]
@germsb can you try `0.3.23` ? You need to remove `data-vue-meta-server-rendered` attribute in `src/index.html`

**Comment by germsb** [comment]
Work great, thank you very much !
