### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by julihermes** [vueneue/vueneue#58]
First, thanks for this plugin!
I have a project using Foundation to make the frontend screens, so I needed SEO infos and a I installed this plugin, when I try access any route, I have this error

```
export {Foundation};
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
...
```
Anybody have any ideia to resolve this issue?

**Comment by chymz** [comment]
Like on UVue, hard to help without code or a reproduction link... share more and maybe I'll be able to help!

**Comment by julihermes** [comment]
I migrate to UVue, you can close this.
Thanks!
