### ISSUE TITLE
how to use context in head configuration

### ISSUE THREAD

**Issue by uncleGena** [vueneue/vueneue#59]
Hi! On this [page](https://vueneue.github.io/docs/guide/ssr.html#head-metas-configuration) described how to use `head: {}` option. But how to make dynamic title tag or use `this.` context or use object from `asyncData()` inside `head:` option ?

```
head() {
  return {}
}
```
either 
```
metaInfo() { return {}}
```
did not work on server side

**Comment by chymz** [comment]
Hi,

I have no problem with this, on new project, in `src/views/Home.vue`:

```js
// @ is an alias to /src
import HelloWorld from "@/components/HelloWorld.vue";

export default {
  name: "home",
  components: {
    HelloWorld
  },

  async asyncData() {
    return {
      foo: "bar"
    };
  },

  head() {
    return {
      title: this.foo
    };
  }
};
```

As a side note, you may be interested on new viersion of this plugin, see #57
