### ISSUE TITLE
More flexible middleware configuration

### ISSUE THREAD

**Issue by kwiniarski** [vueneue/vueneue#7]
Can you consider more flexible way of configuring middleware? By more flexible I mean a way to put some middleware before one which is used by default: https://github.com/vueneue/vueneue/blob/eca14c221dfc67952d33707f19dc1cb44ba62128/packages/%40vueneue/ssr-server/lib/index.js#L51
If I would like to add for example `koa-morgan` then all requests served by `serve` wont appear in the log. I can think of 3 possible solutions:
1. Put lines with custom middleware before `serve`
https://github.com/vueneue/vueneue/blob/eca14c221dfc67952d33707f19dc1cb44ba62128/packages/%40vueneue/ssr-server/lib/index.js#L54-L57 However this solution may be also inconvenient as you may run unnecessary middleware for static files.
2. Move `serve` to `neue.config.js`. Most flexible, however this file needs to be created. Currently when you stick to the defaults this file is not needed at all.
3. Use concept form LoopBack framework, where middleware is injected in several points. In most simple form instead of `ssr.server` there could be something like `ssr.beforeServer` and `ssr.afterServer`. One would be executed before anything else and another one just before render. Of course you can also think about better naming for those hooks.

**Comment by chymz** [comment]
Hi !
I think i'll do your first solution for the next release.

Then I will implement your third proposal later, I need to think about it.

Thanks for the feedback !

**Comment by chymz** [comment]
First proposal done in `0.3.7`

**Comment by camwhite** [comment]
hi @ishitatsuyuki I am under the impression that when running as a PWA there is need for `noCache` headers.

https://github.com/vuejs-templates/pwa/issues/70

Am I wrong about this?

I currently apply this[https://www.npmjs.com/package/koa-no-cache] middlleware globally to the koa instance.

**Comment by ishitatsuyuki** [comment]
@camwhite For service worker entrypoints (and also files like favicon), yes it needs no-cache because it's not chunk hashed. On the other hand, chunk hashed bundles should be forever-cached on CDN to improve delivery speed.

**Comment by chymz** [comment]
Implemented in [UVue](https://github.com/universal-vue/uvue) via server plugins
