### ISSUE TITLE
Is there a way to pass Apollo initial state?

### ISSUE THREAD

**Issue by gcoda** [vueneue/vueneue#8]
Using vuex state for this, [htmlBuilder.js](https://gist.github.com/gcoda/ff330803b779a20eaba46fbff9eb7854#file-htmlbuilder-js-L33-L38)
```javascript
// ssr-server/lib/htmlBuilder.js
if (ssrContext.state.apollo) {
    body += `<script>window.__APOLLO_STATE__=${jsonEncode(
      ssrContext.state.apollo
    )}</script>`
    delete ssrContext.state.apollo
  }
```

**Comment by chymz** [comment]
I'm not very familiar Apollo, can you share some docs/links ?

GraphQL / Apollo is on my roadmap

**Comment by gcoda** [comment]
[vue-apollo](https://akryum.github.io/vue-apollo/guide/ssr.html#on-the-server)
[vue-cli-plugin-apollo](https://github.com/Akryum/vue-cli-plugin-apollo)

**Comment by chymz** [comment]
Thanks, I'll take a look next week

**Comment by gcoda** [comment]
vue-apollo code from ssr guide works inside vueneue middleware like a charm.
Reuse of vuex.state bothers me, but it works.

**Comment by chymz** [comment]
Can you share a repo for this ? I'm curious :smile:

**Comment by gcoda** [comment]
my [main.js](https://gist.github.com/gcoda/ff330803b779a20eaba46fbff9eb7854#file-main-js) in a gist i linked in a first post. 
Will make a clean repo with example graphql server a bit later, i already made a bunch of irrelevant changes.

**Comment by chymz** [comment]
Oh I didn't see gist link, sorry !

Great, thanks a lot, it gives me tracks to work on it

**Comment by chymz** [comment]
Hi @gcoda !

VueNeue is now compatible with Apollo plugin in release `0.3.13` :champagne: 

This was a bit hard but it works !

[You can see the VueNeue plugin here](https://github.com/vueneue/vueneue/blob/master/packages/%40vueneue/vue-cli-plugin-ssr/generator/templates/apollo/src/plugins/apollo.js)
[And code changes to do to `src/vue-apollo.js`](https://vueneue.github.io/docs/guide/cli-plugins.html#apollo)

But you have nothing to do if you add VueNeue after Apollo plugin, all is handled automatically !
